language: node_js

sudo: false

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphicsmagick
  ssh_known_hosts: github.com

install:
  - npm install --no-optional

script:
  - npm run build

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master